# Generated by Django 4.0.8 on 2022-12-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="temp"),
        ),
    ]
