# Generated by Django 4.0.8 on 2022-12-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0005_remove_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
